In [1]:
# Importing testfunctions and algorithms
import numpy as np

import TestFunctionsAndBoundaries.TestFunctions as tf

from Algorithms.PSO import PSO
from Algorithms.GA import GA
from Algorithms.SA import SA
from Algorithms.TS import TS 


In [3]:
# Testing functions
print(PSO(tf.Ackley, tf.Ackley_bounds, 10))
print(GA(tf.Ackley, tf.Ackley_bounds, 10))
print(GA(tf.Ackley, tf.Ackley_bounds, 10))
print(TS(tf.Ackley, tf.Ackley_bounds, 10))

[ -7.63782906   2.1723593   15.0264978  -15.71143062   1.73801142
  20.98341567   8.30233836  -8.08383174   4.71522102 -15.8524336 ]
[  4.07942925   5.53508823  -3.69088005  -7.44656893  -1.30487493
   7.42158364   4.39211342 -16.63535859  -1.26175487   1.46150581]
[-3.02615793  5.37847157  0.79178497  0.15805457  5.17266352  7.36373288
 -6.98793596 10.80543003  4.68435622 -5.1567931 ]
[-0.09257796  0.02894317  0.02958946 -0.04269387  0.03954437  0.10103799
 -0.00592808 -0.07339703  0.17321468  0.04464284]


In [7]:
benchmark_functions = [("Sphere", tf.Sphere, tf.Sphere_bounds, tf.Sphere_opt), 
                       ("Elliptic", tf.Elliptic, tf.Elliptic_bounds, tf.Elliptic_opt),
                       ("Rastrigin", tf.Rastrigin, tf.Rastrigin_bounds, tf.Rastrigin_opt),
                       ("Ackley", tf.Ackley, tf.Ackley_bounds, tf.Ackley_opt),
                       ("Schwefel_1_2", tf.Schwefel_1_2, tf.Schwefel_1_2_bounds, tf.Schwefel_1_2_opt),
                       ("Schwefel", tf.Schwefel, tf.Schwefel_bounds, tf.Schwefel_opt),
                       ("Rosenbrock", tf.Rosenbrock, tf.Rosenbrock_bounds, tf.Rosenbrock_opt),
                       ("Griewank", tf.Griewank, tf.Griewank_bounds, tf.Griewank_opt),
                       ("Sum_of_different_powers", tf.Sum_of_different_powers, tf.Sum_of_different_powers_bounds, tf.Sum_of_different_powers_opt),
                       ("Sum_squares", tf.Sum_squares, tf.Sum_squares_bounds, tf.Sum_squares_opt)]


In [9]:
for name, fit_func, bounds, opt in benchmark_functions:
    print("--- " + name +  " ---")
    print("PSO results: ", fit_func(PSO(fit_func, bounds, 2)))
    print("Actual Optimum: ", opt)
    print("\n")

--- Sphere ---
PSO results:  0.02640540991564709
Actual Optimum:  0


--- Elliptic ---
PSO results:  108.09439513209094
Actual Optimum:  0


--- Rastrigin ---
PSO results:  0.20717558628249222
Actual Optimum:  0


--- Ackley ---
PSO results:  9.064213227893493
Actual Optimum:  0


--- Schwefel_1_2 ---
PSO results:  0.0005586612489810812
Actual Optimum:  0


--- Schwefel ---
PSO results:  221.37340156021696
Actual Optimum:  0


--- Rosenbrock ---
PSO results:  0.03567790311955102
Actual Optimum:  0


--- Griewank ---
PSO results:  17.773787708785836
Actual Optimum:  0


--- Sum_of_different_powers ---
PSO results:  0.0
Actual Optimum:  0


--- Sum_squares ---
PSO results:  0.004234450100763568
Actual Optimum:  0




In [67]:
data_viz = PSO(tf.Ackley, tf.Ackley_bounds, 2, v_max = 10, iterations = 10, visualize = True)
data_viz

[array([ 0.49339519, -0.92310544]),
 array([-0.05458241,  1.13798504]),
 array([-0.09447907, -0.93436575]),
 array([-0.09447907, -0.93436575]),
 array([-0.09447907, -0.93436575]),
 array([-0.09447907, -0.93436575]),
 array([-0.09447907, -0.93436575]),
 array([-0.18108379,  0.28158845]),
 array([-0.18108379,  0.28158845]),
 array([-0.18108379,  0.28158845])]